server:
  port: 16763
spring:
  application:
    name: product-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#配置hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
